# Generated by Django 4.2.13 on 2025-09-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_notice_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='file',
            field=models.FileField(blank=True, help_text='Upload MP4/WebM etc. Leave empty if using a URL.', null=True, upload_to='videos'),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(blank=True, help_text='YouTube/Vimeo or direct URL. Leave empty if uploading a file.'),
        ),
    ]
