# Generated by Django 4.2.13 on 2025-09-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_album_options_alter_galleryimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='description_si',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='album',
            name='title_si',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='address_si',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='organization_si',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='downloadcategory',
            name='description_si',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='downloadcategory',
            name='name_si',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='description_si',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='title_si',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='externallink',
            name='name_si',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='caption_si',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='button_label_si',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='subtitle_si',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='title_si',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='news',
            name='content_si',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='news',
            name='excerpt_si',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_si',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='notice',
            name='content_si',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='title_si',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='publication',
            name='description_si',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_si',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='stat',
            name='label_si',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='stat',
            name='value_si',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='video',
            name='description_si',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='video',
            name='title_si',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
