# Generated by Django 4.2.13 on 2025-09-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_album_description_si_album_title_si_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('nav_label', models.CharField(max_length=255)),
                ('nav_label_si', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('title_si', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('body_si', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About section',
                'verbose_name_plural': 'About sections',
                'ordering': ['position', 'nav_label'],
            },
        ),
        migrations.CreateModel(
            name='HeroIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('heading_si', models.CharField(blank=True, max_length=255)),
                ('highlight', models.CharField(blank=True, max_length=255)),
                ('highlight_si', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('description_si', models.TextField(blank=True)),
                ('primary_label', models.CharField(blank=True, max_length=120)),
                ('primary_label_si', models.CharField(blank=True, max_length=120)),
                ('primary_url', models.URLField(blank=True)),
                ('secondary_label', models.CharField(blank=True, max_length=120)),
                ('secondary_label_si', models.CharField(blank=True, max_length=120)),
                ('secondary_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hero intro',
                'verbose_name_plural': 'Hero intro',
            },
        ),
        migrations.CreateModel(
            name='SiteTextSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=150, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField(blank=True)),
                ('text_si', models.TextField(blank=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Site text snippet',
                'verbose_name_plural': 'Site text snippets',
                'ordering': ['key'],
            },
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'verbose_name': 'Downloadable file', 'verbose_name_plural': 'Downloadable files'},
        ),
    ]
