# Generated by Django 4.2.13 on 2025-09-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_aboutsection_herointro_sitetextsnippet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryPublicationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('name_si', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('description_si', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField(default=0, help_text='Order categories by this field (ascending).')),
            ],
            options={
                'verbose_name': 'Book category',
                'verbose_name_plural': 'Book categories',
                'db_table': 'library_publicationcategory',
                'ordering': ['position', 'name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LibraryPublicationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('title_si', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('subtitle_si', models.CharField(blank=True, max_length=255)),
                ('authors', models.CharField(blank=True, help_text='Comma-separated author names', max_length=255)),
                ('authors_si', models.CharField(blank=True, help_text='Sinhala author names (optional)', max_length=255)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('description_si', models.TextField(blank=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='publication_covers/')),
                ('pdf_file', models.FileField(blank=True, help_text='Optional PDF for the book', null=True, upload_to='publications/')),
                ('external_url', models.URLField(blank=True, help_text='If provided, link to this instead of pdf_file')),
                ('published_at', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in homepage Publications section')),
            ],
            options={
                'verbose_name': 'Book (Library)',
                'verbose_name_plural': 'Books (Library)',
                'db_table': 'library_publicationentry',
                'ordering': ['-published_at', '-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LibraryPublicationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='publication_images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('caption_si', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Publication Image',
                'verbose_name_plural': 'Publication Images',
                'db_table': 'library_publicationimage',
                'ordering': ['created_at'],
                'managed': False,
            },
        ),
    ]
