# Generated by Django 4.2.13 on 2025-09-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_librarypublicationcategory_librarypublicationentry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('title_si', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('body_si', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Footer about',
                'verbose_name_plural': 'Footer about',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Decimal latitude (e.g. 7.290572)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Decimal longitude (e.g. 80.633728)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='map_zoom',
            field=models.PositiveSmallIntegerField(default=15, help_text='Map zoom level for embeds (1-20)'),
        ),
    ]
