# Generated by Django 4.2.13 on 2025-09-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_footerabout_contactinfo_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('name_si', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField()),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Footer link',
                'verbose_name_plural': 'Footer links',
                'ordering': ['position', 'name'],
            },
        ),
    ]
