# Generated by Django 4.2.13 on 2025-09-19 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_footerlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='department',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='publication',
            name='department_si',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
