# Generated by Django 4.2.13 on 2025-09-19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_publication_department_publication_department_si'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='news/gallery')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('caption_si', models.CharField(blank=True, max_length=255)),
                ('position', models.PositiveIntegerField(default=0)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='content.news')),
            ],
            options={
                'verbose_name': 'News image',
                'verbose_name_plural': 'News images',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NoticeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='notice/gallery')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('caption_si', models.CharField(blank=True, max_length=255)),
                ('position', models.PositiveIntegerField(default=0)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='content.notice')),
            ],
            options={
                'verbose_name': 'Notice image',
                'verbose_name_plural': 'Notice images',
                'ordering': ['position', 'id'],
            },
        ),
    ]

